#
# Copyright (C) 2007, 2008, 2009 Fujitsu Limited. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# Further, this software is distributed without any warranty that it is
# free of the rightful claim of any third person regarding infringement
# or the like.  Any license provided herein, whether implied or
# otherwise, applies only to this software file.  Patent licenses, if
# any, provided herein do not apply to combinations of this program with
# other software, or any other product whatsoever.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston MA 02111-1307, USA.
#
##############################################################################

PERL	= /usr/bin/perl
POD2HTML= -$(PERL) -e 'use Pod::Html; pod2html("--noindex", @ARGV);'

IFILE = INDEX
TITLE = "SCTP Conformance Test For User Data Transfer"

document:
	$(AUTORUN) -g -title=$(TITLE) $(IFILE)
	rm -f pod2html-dircache pod2html-itemcache pod2htmd.tmp  pod2htmi.tmp

document2:
	$(AUTORUN) -G $(IFILE)
	rm -f pod2html-dircache pod2html-itemcache pod2htmd.tmp  pod2htmi.tmp

clean:
	-/bin/rm -f *.log *.dump [0-9]*.html index.html summary.html report.html

cleandoc:
	-/bin/rm -f *.html

v4test: changever4 test

v6test: changever6 test

test:
	$(AUTORUN) $(AROPT) -title=$(TITLE) $(IFILE)

changever4:
	../config/chgversion.pl IPv4

changever6:
	../config/chgversion.pl IPv6

tahi:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -dump2txt -title=$(TITLE) $(IFILE)

tiny:	document
	/bin/rm -f index.html summary.html report.html
	$(AUTORUN) $(AROPT) -dump2txt -tiny -title=$(TITLE) $(IFILE)

include ../Makefile.inc
